import "../styles/globals.css";

import type { AppProps } from "next/app";
import Head from "next/head";
import { Provider } from "next-auth/client";
import { initializeIcons } from "@fluentui/react";

function MyApp({ Component, pageProps }: AppProps) {
  initializeIcons();
  return (
    <Provider session={pageProps.session}>
      <Head>
        <title>PILTOVER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Provider>
  );
}
export default MyApp;
